#!/bin/sh -l

./config.sh --url ./config.sh --url $REPO_URL --token "BHCAUWD46GKUKFXMSFCEBTTF7JWFBAVPNFXHG5DBNRWGC5DJN5XF62LEZYBOK3VFWFUW443UMFWGYYLUNFXW4X3UPFYGLN2JNZ2GKZ3SMF2GS33OJFXHG5DBNRWGC5DJN5XA" --unattended --ephemeral && ./run.sh
